server:
  port: 8999
spring:
  application:
    name: semi-sample
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: SEMISAMPLE
    password: SEMISAMPLE
mybatis:
  configuration:
    jdbc-type-for-null: null
    map-underscore-to-camel-case: true
  type-aliases-package: com.adele.semisample
  mapper-locations: classpath:mapper/*.xml
